name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      # 1. Common must be built first because backend, npm-app, and web reference it
      - name: Build "common" package
        run: bun run --cwd common build

      # 2. Then build + type-check "backend"
      - name: Build "backend" package
        run: bun run --cwd backend build

      # 3. Then build + type-check "npm-app"
      - name: Build "npm-app" package
        run: bun run --cwd npm-app build

      # 4. Finally run type-check on "web"
      - name: Type-check "web" package
        run: bun run --cwd web typecheck
